import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { FREECAD_CMD } from './config.mjs';
import { slugify } from './utils.mjs';

const execFileAsync = promisify(execFile);

function createFreeCadScript(spec) {
  const safe = JSON.stringify(spec, null, 2);
  return `# Generated by Natural Building Design Dashboard
# FreeCAD-first BIM coordination model. Units: millimeters.
import json
import FreeCAD as App
import Part

SPEC = json.loads(r'''${safe}''')
MM_PER_FOOT = 304.8

def ft(value):
    return float(value or 0) * MM_PER_FOOT

def clean(value):
    return "".join(ch if ch.isalnum() else "_" for ch in str(value or "Object")).strip("_") or "Object"

def add_box(group, name, x, y, z, sx, sy, sz, color):
    obj = doc.addObject("Part::Box", clean(name))
    obj.Label = name
    obj.Length = max(1, sx)
    obj.Width = max(1, sy)
    obj.Height = max(1, sz)
    obj.Placement.Base = App.Vector(x, y, z)
    try:
        obj.ViewObject.ShapeColor = color
    except Exception:
        pass
    group.addObject(obj)
    return obj

doc = App.newDocument(clean(SPEC.get("projectName", "Natural_Building_Model")))
site = doc.addObject("App::DocumentObjectGroup", "IFC_Site")
building = doc.addObject("App::DocumentObjectGroup", "IFC_Building")
site.addObject(building)
level = doc.addObject("App::DocumentObjectGroup", "Level_01")
building.addObject(level)
site_elements = doc.addObject("App::DocumentObjectGroup", "Site_Outdoor_Elements")
site.addObject(site_elements)
schedules = doc.addObject("App::DocumentObjectGroup", "Schedules_And_QA")
building.addObject(schedules)

shell = SPEC.get("shell", {})
width = ft(shell.get("widthFt", 36))
depth = ft(shell.get("depthFt", 28))
pad = ft(shell.get("padExtensionFt", 64))
wall_h = ft(shell.get("wallHeightFt", 10))
south_h = ft(shell.get("southWallHeightFt", shell.get("wallHeightFt", 10)))
north_h = ft(shell.get("northWallHeightFt", shell.get("wallHeightFt", 10)))
wall_t = ft(1.5 if "straw" in SPEC.get("systems", {}).get("envelope", "").lower() else 0.55)
slab_t = ft(0.5)

add_box(level, "bim_pad_site_slab", -pad, -pad, 0, width + pad * 2, depth + pad * 2, slab_t, (0.62, 0.60, 0.53))
add_box(level, "wall_north_" + clean(SPEC.get("systems", {}).get("envelope", "assembly")), 0, 0, slab_t, width, wall_t, north_h, (0.76, 0.60, 0.34))
add_box(level, "wall_south_" + clean(SPEC.get("systems", {}).get("envelope", "assembly")), 0, depth - wall_t, slab_t, width, wall_t, south_h, (0.76, 0.60, 0.34))
add_box(level, "wall_west_" + clean(SPEC.get("systems", {}).get("envelope", "assembly")), 0, 0, slab_t, wall_t, depth, max(south_h, north_h), (0.76, 0.60, 0.34))
add_box(level, "wall_east_" + clean(SPEC.get("systems", {}).get("envelope", "assembly")), width - wall_t, 0, slab_t, wall_t, depth, max(south_h, north_h), (0.76, 0.60, 0.34))

for room in SPEC.get("rooms", []):
    add_box(level, "space_" + room.get("id", room.get("name", "room")), ft(room.get("x", 0)), ft(room.get("y", 0)), slab_t + 15, ft(room.get("w", 1)), ft(room.get("d", 1)), 45, (0.37, 0.58, 0.62))

for element in SPEC.get("elements", []):
    group = site_elements if element.get("category") in ["site", "garden", "animal", "landscape", "homestead"] or element.get("type") in ["outdoor", "site", "garden", "animal"] else level
    add_box(group, "element_" + element.get("id", element.get("name", "element")), ft(element.get("x", 0)), ft(element.get("y", 0)), slab_t + ft(element.get("z", 0)), ft(element.get("w", 1)), ft(element.get("d", 1)), ft(element.get("h", 1)), (0.43, 0.36, 0.24))

for opening in SPEC.get("openings", []):
    wall = opening.get("wall", "south")
    along = ft(opening.get("x", opening.get("y", 0)))
    size = ft(opening.get("widthFt", 3))
    name = "opening_" + clean(opening.get("label", opening.get("type", "opening")))
    if wall in ["north", "south"]:
        y = -ft(0.2) if wall == "north" else depth
        add_box(level, name, along, y, slab_t + ft(3), size, ft(0.3), ft(4), (0.20, 0.48, 0.72))
    else:
        x = width if wall == "east" else -ft(0.2)
        add_box(level, name, x, along, slab_t + ft(3), ft(0.3), size, ft(4), (0.20, 0.48, 0.72))

roof = doc.addObject("Part::Feature", clean("roof_" + shell.get("roofType", "gable")))
if shell.get("roofType") == "shed":
    pts = [
        App.Vector(-ft(2), -ft(2), slab_t + north_h + ft(0.3)),
        App.Vector(width + ft(2), -ft(2), slab_t + north_h + ft(0.3)),
        App.Vector(width + ft(2), depth + ft(2), slab_t + south_h + ft(0.3)),
        App.Vector(-ft(2), depth + ft(2), slab_t + south_h + ft(0.3)),
    ]
    roof.Shape = Part.Face(Part.makePolygon([pts[0], pts[1], pts[2], pts[3], pts[0]]))
else:
    rise = depth * float(shell.get("roofPitch", 0.32))
    pts = [
        App.Vector(-ft(2), -ft(2), slab_t + wall_h),
        App.Vector(width + ft(2), -ft(2), slab_t + wall_h),
        App.Vector(width + ft(2), depth / 2, slab_t + wall_h + rise),
        App.Vector(-ft(2), depth / 2, slab_t + wall_h + rise),
        App.Vector(-ft(2), depth + ft(2), slab_t + wall_h),
        App.Vector(width + ft(2), depth + ft(2), slab_t + wall_h),
    ]
    roof.Shape = Part.Compound([
        Part.Face(Part.makePolygon([pts[0], pts[1], pts[2], pts[3], pts[0]])),
        Part.Face(Part.makePolygon([pts[3], pts[2], pts[5], pts[4], pts[3]])),
    ])
level.addObject(roof)

summary = doc.addObject("App::FeaturePython", "BIM_Operation_Summary")
summary.addProperty("App::PropertyString", "ProjectName", "BIM").ProjectName = SPEC.get("projectName", "")
summary.addProperty("App::PropertyString", "Envelope", "BIM").Envelope = SPEC.get("systems", {}).get("envelope", "")
summary.addProperty("App::PropertyString", "Structure", "BIM").Structure = SPEC.get("systems", {}).get("structure", "")
schedules.addObject(summary)

doc.recompute()
out_path = SPEC.get("_freecadOutputPath") or (clean(SPEC.get("projectName", "Natural_Building_Model")) + "_Rev" + str(SPEC.get("revision", 1)) + ".FCStd")
doc.saveAs(out_path)
print("FREECAD_EXPORT_PATH=" + out_path)
`;
}

export async function exportFreeCadModel(spec) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'natural-bim-'));
  const project = slugify(spec?.projectName || 'natural-building-model');
  const scriptPath = path.join(dir, `${project}-rev-${spec?.revision || 1}.py`);
  const fcstdPath = path.join(dir, `${project}-rev-${spec?.revision || 1}.FCStd`);
  const scriptSpec = { ...spec, _freecadOutputPath: fcstdPath };
  await fs.writeFile(scriptPath, createFreeCadScript(scriptSpec), 'utf8');
  const result = {
    scriptPath,
    fcstdPath,
    freecadCmd: FREECAD_CMD,
    ran: false,
    ok: false,
    stdout: '',
    stderr: '',
    warnings: [],
    objectCount: 0
  };
  try {
    const { stdout, stderr } = await execFileAsync(FREECAD_CMD, [scriptPath], { timeout: 120000 });
    result.ran = true;
    result.ok = true;
    result.stdout = stdout;
    result.stderr = stderr;
  } catch (error) {
    result.ran = true;
    result.ok = false;
    result.stdout = error?.stdout || '';
    result.stderr = error?.stderr || error?.message || String(error);
    result.warnings.push('FreeCAD command did not complete successfully. The generated Python script was still saved.');
  }
  result.objectCount = 1 + 4 + (spec?.rooms || []).length + (spec?.elements || []).length + (spec?.openings || []).length + 1;
  return result;
}
